### ISSUE TITLE
Swaync font and firefox tabs

### ISSUE THREAD

**Issue by ispanos** [lvntcnylmz/dotfiles#1]
Hello,

I found your repo in the swaync readme after someone shared their set-up with your swaync config. You have some nice looking configs here.

I have a couple of questions.

1. What font do you use for the swaync panel? Installed `jetbrains-mono-fonts-all` on Fedora, but I'm missing the labels in your config.json.

2. Do you have a way to see all open tabs on firefox with your config? I can blindly cycle through them, but can see a list of what's open. Also, I am missing the [column](https://github.com/lvntcnylmz/dotfiles/blob/main/screenshots/sway-4.png) on the left hand side of the window.

Thanks for all the great stuff here.

**Comment by lvntcnylmz** [comment]
Hi @ispanos, First of all, thank you for your kind words and greetings from the neighbor. (:tr:  Turkey) :smile: 

1.  I don't use Fedora, so I have no idea if the package I'm using is available in the Fedora package repository. But the font   package I use is ttf-jetbrains-mono-nerd. [Here](https://www.nerdfonts.com/font-downloads) you can search and install directly.
2.   I configured the tab extension for my daily use, but if you follow the "How to Install" section in the README file [in this repository](https://github.com/ranmaru22/firefox-vertical-tabs), you will get the config you want.

If there's anything else I can help you with, please don't hesitate to ask. :+1:

**Comment by ispanos** [comment]
Thanks for the reply. Everything when great with the tabs addon. Although I could automate loading `tabCenterReborn.min.css` after a fresh install.

I will check out the fonts later. I've never installed fonts without using the package manager.

**Comment by lvntcnylmz** [comment]
You can check Fedora's [documentation](https://docs.fedoraproject.org/en-US/quick-docs/fonts/) for font installation.
