### ISSUE TITLE
What Icon should one use to replicate the swaync config?

### ISSUE THREAD

**Issue by pdx2hyd** [lvntcnylmz/dotfiles#2]
For example, the label icon is unknown on my system. Need some advice on which icons or fonts to install. Thank you.
      "label": "󰍬",
          "command": "pactl set-source-mute @DEFAULT_SOURCE@ toggle"

**Comment by lvntcnylmz** [comment]
On my system I use JetBrainsMono Nerd Font as a font and Nerd Font icons as icons.
- You can check [here](https://www.nerdfonts.com/font-downloads) for fonts.
- You can also find the icons [here](https://www.nerdfonts.com/cheat-sheet)
